users:
  - name: app
    passwordSecret:
      name: my-app-passwords
      keys:
        - app
    commands:
      allow:
        - "+@all"
      deny:
        - "-@dangerous"
    keys:
      readWrite:
        - "~*"
