autoscaling:
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPU: 60
    targetMemory: 70
  vpa:
    enabled: true
    annotations:
      foo: bar
    controlledResources:
      - cpu
      - memory
    maxAllowed:
      cpu: "1"
      memory: 1Gi
    minAllowed:
      cpu: 100m
      memory: 128Mi
    updatePolicy:
      updateMode: "Off"
