apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" . ) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  imageName: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  instances: {{ .Values.replicaCount }}
  storage:
    size: {{ .Values.persistence.size }}
    {{- with include "common.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) }}
    storageClass: {{ index (. | fromYaml) "storageClassName" }}
    {{- end }}
  {{- with .Values.bootstrap }}
  bootstrap: {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if eq .Values.certificates.mode "cert-manager" }}
  certificates:
    serverTLSSecret: {{ template "common.names.fullname" . }}-server
    serverCASecret: {{ template "common.names.fullname" . }}-server
    clientCASecret: {{ template "common.names.fullname" . }}-replication
    replicationTLSSecret: {{ template "common.names.fullname" . }}-replication
  {{- end }}
  affinity:
    podAntiAffinityType: {{ .Values.affinity.podAntiAffinityType }}
    {{- with .Values.affinity.topologyKey }}
    topologyKey: {{ . }}
    {{- end }}
  {{- with .Values.topologySpreadConstraints }}
  topologySpreadConstraints: {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled }}
  monitoring:
    enablePodMonitor: true
  {{- end }}
  {{- if .Values.backup.enabled }}
  plugins:
    - name: {{ .Values.backup.pluginName | quote }}
      isWALArchiver: true
      parameters:
        barmanObjectName: {{ template "common.names.fullname" . }}-backup
  {{- end }}
  {{- with .Values.resources }}
  resources: {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
