{{- if .Values.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" . ) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end  }}
  {{- if or .Values.pdb.maxUnavailable ( not .Values.pdb.minAvailable ) }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
  {{- end  }}
  {{- with .Values.pdb.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . | quote }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
{{- end }}
